AWSTemplateFormatVersion: "2010-09-09"
Description: "Dynamo DB Creation Sample"
Resources:
  personDynamoDB:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "person"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "person"
          KeyType: "HASH"
      BillingMode: "PAY_PER_REQUEST"
      TableName: "Persons"
  addressDynamoDB:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "address"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "address"
          KeyType: "HASH"
      BillingMode: "PAY_PER_REQUEST"
      TableName: "Addresses"
Outputs:
  PersonDbOutput:
    Value: !GetAtt personDynamoDB.Arn
    Description: "person DB logic"
  AddressDbOutput:
    Value: !GetAtt addressDynamoDB.Arn
    Description: "address DB logic"